### ISSUE TITLE
chore(install): prompt user for angular module type

### ISSUE THREAD

**Issue by pgilad** [mgcrea/generator-angular-component#12]
User should be prompt:

```
What kind of Angular module is it?
- Directive
- Factory
- Service
- Filter
```

And the relevant module should be generated in main .js file.
Also the test file generated should match the module type.

For reference we can use:
https://github.com/azzamallow/generator-angulator/blob/master/app/index.js#L37

Which appears to be a dead project, but does the generator right...

**Comment by mgcrea** [comment]
Good idea, do you feel like making theses changes?

**Comment by pgilad** [comment]
https://github.com/mgcrea/generator-angular-component/pull/15
