### ISSUE TITLE
discussion: having seconds thoughts about this

### ISSUE THREAD

**Issue by pgilad** [mgcrea/generator-angular-component#18]
Why not merge this into generator-angular? Basically we are creating the same thing as them - and they probably do it better.

Also - their tests are probably better generated.

So the only thing that defines this generator is it being aimed at small angular bower components. Does it justify being a stand-alone generator?

**Comment by mgcrea** [comment]
Because it perfectly suits my needs, `generator-angular` appeared too bloated the last time I used it. My projects are mainly a reflection of my professional needs that are often time-critical. Feel free to contribute back to the official angular-generator if you want, that would indeed be nice.

**Comment by mgcrea** [comment]
@pgilad Also the scope is not exactly the same, as `generator-angular` gives you a "working" app, this generator is to bootstrap isolated components.

**Comment by pgilad** [comment]
@mgcrea but you can use their `yo angular:component` method?
