### ISSUE TITLE
Deprecated karma configuration file

### ISSUE THREAD

**Issue by matteosuppo** [mgcrea/generator-angular-component#5]
The karma configuration syntax has slightly changed: https://github.com/karma-runner/karma/blob/master/test/client/karma.conf.js

As a result when launching the command `grunt test` the following happens:

```
WARN [config]: JASMINE is not supported anymore. Please use:
  module.exports = function(config) {
    config.set({
      // your config
      frameworks: ["jasmine"]
    });
  };

WARN [config]: JASMINE_ADAPTER is not supported anymore. Please use:
  module.exports = function(config) {
    config.set({
      // your config
      frameworks: ["jasmine"]
    });
  };

WARN [config]: LOG_INFO is not supported anymore.
  Please use `config.LOG_INFO` instead.
ERROR [config]: Config file must export a function!
  module.exports = function(config) {
    config.set({
      // your config
    });
  };
```

Updating the karma.conf.js file according to the new structure does fix everything.

I'm working on a pull request to fix it, if you're interested.

**Comment by mgcrea** [comment]
Had started a rewrite a couple of days ago, just pushed the wip branch so can you can start from that if you want, karma config should be ok.
